# Data sources
The data were collected by two members of the group together. Since our idea at first was to study New York house prices, we chose to collect data from the FRED Economic Data website. However, after we selected the qualifiers and downloaded the data, we found that there was too little data available, so we continued to search for applicable data. After discussion, we decided to download the data from NYC Department of Finance.

We downloaded the data set for each of the five different boroughs from the NYC Department of Finance website and put it in the same file. Before uploading the data sets, we needed to determine if they were available. By comparing the information of the five data sets, we found that the variables are the same for each data set or each borough. These data sets include the neighborhood, building type, square footage, and other data, for a total of 21 variables. The variable types include character, numeric, logical, and the POSIXct, which is the number of seconds since the start of January 1, 1970. Because each data set has the same variables, this facilitates us to merge 5 data sets into one data set, which is convenient to process and analyze the data information. In addition, we added a new column called "Name" to the data set in order to make it more intuitive and clear when representing the boroughs in the later graphs.

However, after we dive into the merged data set, we also found problems. First, the variable "EASEMENT" and the variable "APARTMENT NUMBER" have no data records from the beginning to the end. Second, because the data had not been processed, our observations were too large after data merging, more than 90,000. Thirdly, some variables have more than 40,000 missing values, such as "LAND SQUARE FEET" and "GROSS SQUARE FEET". We will deal with these problems we found in the later part to reduce the complexity and biased possibility.

Here are the links to our data sources and the descriptions of the variables.

Data source:
https://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page

Variable description:
https://www1.nyc.gov/assets/finance/downloads/pdf/07pdf/glossary_rsf071607.pdf

https://www1.nyc.gov/assets/finance/jump/hlpbldgcode.html
