# Conclusion
By charting and analyzing properties price in the five boroughs of New York, we can see that Brooklyn and Queens had the highest rolling home sales in the past year. The lowest is the Bronx, which is only one-fifth of Brooklyn's. We also concluded by looking at house price trends that there is still a covid-19 effect in New York in 2021, so the average rolling house price for the five boroughs is not high. However, by January 2022 to date, the economic impact of the pandemic is significantly lower and the real estate market is showing signs of recovery. Also, we find that Manhattan has the highest rolling home prices of the five New York boroughs, followed by Brooklyn and Queens. It is worth noting that the property prices on Long Island and Flushing are much higher than elsewhere in Queens.

In addition to New York's five boroughs, we further examined home prices from the perspective of four tax types for housing. We learned that the fourth tax property has the most types of houses, of which Office bulidings and warehouses are the most expensive. Nevertheless, the second tax type houses have more number of units, and special condo billing lots are the most prominent in the second category. And the first tax type houses have lower average prices than other types, we think this The reason for this phenomenon is that most people now prefer to live in an apartment rather than an older house with less than three floors. So the first tax type may be phased out from the rolling housing market.

We speculate that in the future real estate market, Brooklyn and Queens houses have more potential and more investment, especially Long Island City and Flushing. But unfortunately, the first tax type of houses may be gradually fading out of the market. In general, we believe that the economic impact of covid-19 on people is gradually fading away, and house prices are gradually returning to their growth trend and will develop rapidly in the next few years.
